"""Generate all paper figures from main experiment results.

Figure 1 — Learning curves: mean normalised regret vs BO budget (5–100)
           for all methods across 5 scenarios. 5-panel grid.
           Saves: figures/fig1_learning_curves.pdf

Figure 2 — CD diagram (already generated by stats_cd.py).
           figures/cd_diagram.pdf

Figure 3 — DDF probe summary: scatter of (AQ, d) per task, coloured by regime.
           Saves: figures/fig3_ddf_probes.pdf

Usage:
    cd <project root>
    PYTHONPATH=src:scripts python3 scripts/generate_figures.py
"""
from __future__ import annotations

import sys
import json
from pathlib import Path
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.lines as mlines

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

import tensorize
from prep import Problem
from ddf import recommend

RESULTS_DIR = ROOT / "results" / "raw" / "main"
FIGURES_DIR = ROOT / "figures"
K0_DDF      = 5

SCEN_ORDER = ["rbv2_svm_radial", "rbv2_glmnet", "rbv2_rpart",
              "rbv2_ranger",     "lcbench"]

SCEN_LABELS = {
    "rbv2_svm_radial": "SVM radial (d=2, 399 cells)",
    "rbv2_glmnet":     "Glmnet (d=2, 225 cells)",
    "rbv2_rpart":      "Rpart (d=4, 28,561 cells)",
    "rbv2_ranger":     "Ranger (d=3, 729 cells)",
    "lcbench":         "LCBench (d=7, 233,280 cells)",
}

BUDGETS = [5, 10, 15, 25, 50, 100]

# Colour + style palette (14 methods)
PALETTE = {
    "rs":                ("#aaaaaa", "-",  1.0, "RS"),
    "bo_cold":           ("#555555", "--", 1.2, "BO-Cold"),
    "tpe":               ("#e67e22", "-",  1.5, "TPE"),
    "active_pmf":        ("#27ae60", "-",  1.5, "Active-PMF"),
    "rgpe":              ("#8e44ad", "-",  1.8, "RGPE"),
    "lrtc_oneshot":      ("#c0392b", ":",  1.2, "LRTC-Oneshot"),
    "bo_lrtc_prior":     ("#2980b9", "--", 1.2, "BO-LRTC-Prior"),
    "bo_lrtc_refit":     ("#1abc9c", "--", 1.2, "BO-LRTC-Refit"),
    "bo_lrtc_pibo":      ("#f39c12", "--", 1.2, "BO-LRTC-piBO"),
    "bo_lrtc_hybrid":    ("#d35400", "--", 1.2, "BO-LRTC-Hybrid"),
    "bo_lrtc_portfolio": ("#7f8c8d", "-.", 1.3, "BO-LRTC-Portfolio"),
    "bo_pmf_prior":      ("#16a085", "-.", 1.2, "BO-PMF-Prior"),
    "bo_lrtc_feature":   ("#2c3e50", "-",  2.2, "BO-LRTC-Feature"),
    "ddf":               ("#e74c3c", "-",  2.5, "DDF-Oracle"),
}

# Subset for cleaner learning curve plots (avoid clutter)
HIGHLIGHT = ["rs", "bo_cold", "tpe", "active_pmf", "rgpe",
             "bo_lrtc_feature", "ddf"]


# ── 1. Load per-task, per-budget regret ──────────────────────────────────

def load_curves(results_dir: Path, budgets: list[int]) -> dict:
    """Return curves[scenario][method][budget] = mean regret across tasks+seeds."""
    data: dict = {}
    for scen_dir in sorted(results_dir.iterdir()):
        if not scen_dir.is_dir():
            continue
        scen = scen_dir.name
        # method → budget → list of regret values
        method_budget: dict = defaultdict(lambda: defaultdict(list))
        for method_dir in sorted(scen_dir.iterdir()):
            if not method_dir.is_dir():
                continue
            method = method_dir.name
            for fpath in method_dir.glob("*.json"):
                try:
                    with open(fpath) as f:
                        d = json.load(f)
                    regret_map = {cp["budget"]: cp["normalized_regret"]
                                  for cp in d["checkpoints"]}
                    for b in budgets:
                        av = max((k for k in regret_map if k <= b), default=None)
                        if av is None:
                            av = min(regret_map)
                        method_budget[method][b].append(regret_map[av])
                except Exception:
                    continue
        data[scen] = {m: {b: float(np.mean(v))
                          for b, v in bd.items()}
                      for m, bd in method_budget.items()}
    return data


def add_ddf_curves(curves: dict, budgets: list[int]) -> None:
    """Compute DDF learning curve by summing anchors + recommended-method costs."""
    for scenario in SCEN_ORDER:
        if scenario not in curves:
            continue
        gdir = Path(tensorize.grid_dir(ROOT, "paper_d", scenario))
        if not (gdir / "tensor.npz").exists():
            continue
        g = tensorize.load_grid(gdir)
        tensor, task_ids, meta = g["tensor"], g["task_ids"], g["meta"]

        # For each budget: average over test tasks of DDF-recommended regret
        budget_vals: dict = defaultdict(list)
        for task in meta["test_task_ids"]:
            try:
                prob   = Problem(tensor, task_ids, meta["train_task_ids"],
                                 task, k0=K0_DDF)
                rec    = recommend(prob)
                method = rec["recommended"]
                for b in budgets:
                    reg = curves[scenario].get(method, {}).get(b, np.nan)
                    if np.isfinite(reg):
                        budget_vals[b].append(reg)
            except Exception:
                continue

        curves[scenario]["ddf"] = {b: float(np.mean(v))
                                   for b, v in budget_vals.items() if v}


# ── 2. Figure 1: Learning curves ─────────────────────────────────────────

def fig1_learning_curves(curves: dict, out_path: Path) -> None:
    scenarios = [s for s in SCEN_ORDER if s in curves]
    n = len(scenarios)
    fig, axes = plt.subplots(1, n, figsize=(4.5 * n, 3.8), sharey=False)
    if n == 1:
        axes = [axes]

    for ax, scen in zip(axes, scenarios):
        scen_curves = curves[scen]
        all_methods = list(PALETTE.keys())
        # sort so DDF and bo_lrtc_feature are drawn on top
        draw_order = [m for m in all_methods if m not in ("ddf", "bo_lrtc_feature")]
        draw_order += ["bo_lrtc_feature", "ddf"]

        for m in draw_order:
            if m not in scen_curves:
                continue
            if m not in PALETTE:
                continue
            color, ls, lw, label = PALETTE[m]
            bvals = sorted(scen_curves[m].keys())
            yvals = [scen_curves[m][b] for b in bvals]
            alpha = 1.0 if m in ("ddf", "bo_lrtc_feature", "rgpe") else 0.55
            zorder = 5 if m == "ddf" else (4 if m == "bo_lrtc_feature" else 2)
            ax.plot(bvals, yvals, color=color, ls=ls, lw=lw,
                    alpha=alpha, zorder=zorder)

        ax.set_title(SCEN_LABELS[scen], fontsize=8, pad=4)
        ax.set_xlabel("BO budget (# evaluations)", fontsize=7.5)
        ax.set_ylabel("Mean normalised regret", fontsize=7.5)
        ax.set_xlim(BUDGETS[0] - 1, BUDGETS[-1] + 2)
        ax.tick_params(labelsize=7)
        ax.grid(True, ls=":", alpha=0.4, lw=0.6)
        ax.set_yscale("log")
        ax.yaxis.set_minor_locator(matplotlib.ticker.NullLocator())

    # shared legend below figure
    handles = []
    for m, (color, ls, lw, label) in PALETTE.items():
        alpha = 1.0 if m in ("ddf", "bo_lrtc_feature", "rgpe") else 0.6
        h = mlines.Line2D([], [], color=color, ls=ls, lw=lw,
                          alpha=alpha, label=label)
        handles.append(h)

    fig.legend(handles=handles, loc="lower center",
               ncol=7, fontsize=7, frameon=True,
               bbox_to_anchor=(0.5, -0.13))
    fig.suptitle("Learning curves: mean normalised regret@budget",
                 fontsize=9, y=1.01)
    plt.tight_layout(rect=[0, 0.08, 1, 1])
    plt.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"  Saved {out_path}")


# ── 3. Figure 3: DDF probe scatter ───────────────────────────────────────

def fig3_ddf_probes(out_path: Path) -> None:
    """Scatter of (AQ, task_sim) per test task, coloured by DDF regime."""
    REGIME_COLORS = {
        "F": "#27ae60", "E": "#e67e22",
        "G": "#8e44ad", "A": "#2980b9", "A2": "#7f8c8d",
        "B": "#1abc9c", "C": "#c0392b", "D": "#f39c12",
    }
    REGIME_LABELS = {
        "F": "F: active-pmf (d≤2, AQ<0.05)",
        "E": "E: tpe (d≤2, AQ≥0.05)",
        "G": "G: rgpe (d≥6)",
        "A": "A: bo-lrtc-feat (d=3, ceil)",
        "A2": "A2: bo-cold (d=4-5, ceil)",
        "B": "B: bo-lrtc-feat (Tucker)",
        "C": "C: rgpe (task-sim>0.5)",
        "D": "D: bo-lrtc-feat (fallback)",
    }

    points: list[dict] = []
    for scenario in SCEN_ORDER:
        gdir = Path(tensorize.grid_dir(ROOT, "paper_d", scenario))
        if not (gdir / "tensor.npz").exists():
            continue
        g = tensorize.load_grid(gdir)
        tensor, task_ids, meta = g["tensor"], g["task_ids"], g["meta"]
        d = len(tensor.shape) - 1
        for task in meta["test_task_ids"]:
            try:
                prob = Problem(tensor, task_ids, meta["train_task_ids"],
                               task, k0=K0_DDF)
                rec  = recommend(prob)
                points.append({
                    "aq":       rec["aq"],
                    "task_sim": rec["task_sim"] if rec["task_sim"] is not None else -0.05,
                    "d":        d,
                    "regime":   rec["regime"],
                    "scenario": scenario,
                })
            except Exception:
                continue

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    # Left: AQ vs task_sim coloured by regime
    ax = axes[0]
    seen_regimes: set = set()
    for p in points:
        color  = REGIME_COLORS.get(p["regime"], "#333333")
        lbl    = REGIME_LABELS.get(p["regime"], p["regime"])
        marker = {"F": "o", "E": "s", "G": "^",
                  "A": "D", "A2": "v", "B": "P",
                  "C": "X", "D": "*"}.get(p["regime"], "o")
        kw = dict(color=color, marker=marker, s=35, alpha=0.75, linewidths=0.4,
                  edgecolors="white")
        if p["regime"] not in seen_regimes:
            ax.scatter([p["aq"]], [p["task_sim"]], label=lbl, **kw)
            seen_regimes.add(p["regime"])
        else:
            ax.scatter([p["aq"]], [p["task_sim"]], **kw)
    ax.axhline(0.5, color="#aaaaaa", ls="--", lw=0.8, alpha=0.6)
    ax.axvline(0.05, color="#aaaaaa", ls="--", lw=0.8, alpha=0.6)
    ax.set_xlabel("Oracle Anchor Quality (AQ) — Probe 2", fontsize=8.5)
    ax.set_ylabel("Task similarity — Probe 4\n(−0.05 = probe not run)", fontsize=8.5)
    ax.set_title("DDF-Oracle probe values coloured by regime", fontsize=9)
    ax.tick_params(labelsize=7.5)
    ax.grid(True, ls=":", alpha=0.35, lw=0.6)
    ax.legend(fontsize=6.5, loc="upper right", framealpha=0.85, ncol=1)

    # Right: AQ distribution by scenario
    ax2 = axes[1]
    scen_short = {
        "rbv2_svm_radial": "SVM",
        "rbv2_glmnet":     "Glmnet",
        "rbv2_rpart":      "Rpart",
        "rbv2_ranger":     "Ranger",
        "lcbench":         "LCBench",
    }
    scen_colors = ["#e74c3c", "#3498db", "#2ecc71", "#f39c12", "#9b59b6"]
    for i, scen in enumerate(SCEN_ORDER):
        vals = [p["aq"] for p in points if p["scenario"] == scen]
        ax2.hist(vals, bins=15, alpha=0.6, color=scen_colors[i],
                 label=scen_short[scen], density=True, edgecolor="white", lw=0.4)
    ax2.axvline(0.05, color="#555555", ls="--", lw=1.0,
                label="AQ ceiling threshold (0.05)")
    ax2.set_xlabel("Oracle Anchor Quality (AQ) — Probe 2", fontsize=8.5)
    ax2.set_ylabel("Density", fontsize=8.5)
    ax2.set_title("AQ distribution per scenario", fontsize=9)
    ax2.tick_params(labelsize=7.5)
    ax2.grid(True, ls=":", alpha=0.35, lw=0.6)
    ax2.legend(fontsize=7.5, framealpha=0.85)

    plt.tight_layout()
    plt.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close()
    print(f"  Saved {out_path}")


# ── Main ──────────────────────────────────────────────────────────────────

def main():
    FIGURES_DIR.mkdir(exist_ok=True)

    print("Loading learning curves …", flush=True)
    curves = load_curves(RESULTS_DIR, BUDGETS)
    print("Computing DDF curves …", flush=True)
    add_ddf_curves(curves, BUDGETS)

    print("\n── Figure 1: Learning curves ─────────────────────────────────")
    fig1_learning_curves(curves, FIGURES_DIR / "fig1_learning_curves.pdf")

    print("\n── Figure 3: DDF probe scatter ───────────────────────────────")
    fig3_ddf_probes(FIGURES_DIR / "fig3_ddf_probes.pdf")

    print("\nDone. Figures in figures/")


if __name__ == "__main__":
    main()
